


Aviso de Privacidad

La Secretaría de Educación, Ciencia, Tecnología e Innovación de la Ciudad de México, con domicilio en Avenida Chapultepec No 49, Col. Centro, Alcaldía Cuauhtémoc, C.P. 06010, Ciudad de México, es la responsable del tratamiento de los datos personales contenidos en el Sistema de Datos Personales de los  Puntos de Innovación, Libertad, Arte, Educación y Saberes (PILARES), los cuales serán protegidos conforme a lo dispuesto por la Ley de Protección de Datos Personales en posesión de Sujetos Obligados de la Ciudad de México, y demás normatividad aplicable. 

Los datos recabados se utilizarán para la siguiente finalidad: En el caso de los facilitadores, revisar que los interesados reúnen los requisitos para acceder a los beneficios, incorporación a los proyectos, ayudas o servicios que se otorgan en los PILARES, para selección, prelación, verificación, seguimiento, integración de expedientes, integración del padrón de beneficiarios y su publicación en la Gaceta Oficial de la Ciudad de México, para recibir capacitación y contribuir a la profesionalización, para elaboración de reportes, recibir su ayuda social por su aporte, publicación en Internet de la información sobre los montos pagados durante el período por concepto de ayudas conforme a lo establecido en la Ley General de Contabilidad Gubernamental. En el caso de los usuarios, para registro de las personas atendidas, seguimiento y en su caso integración de expediente, de igual manera para su incorporación a proyectos pedagógicos, estudios, actividades de difusión, foros y fortalecimiento de los programas operados por la Coordinación General de Inclusión Educativa e Innovación (CGIEI) de la Secretaría de Educación, Ciencia, Tecnología e Innovación de la Ciudad de México. Así como para fines estadísticos, asignación de claves y contraseñas, soporte técnico, en su caso la elaboración de la evaluación interna y externa, así como para atención de quejas.

Para las finalidades antes señaladas se solicitarán los siguientes datos personales: 1) Los datos recabados de las personas menores de edad o en estado de interdicción usuarios de los PILARES son: A. Datos identificativos: Nombre, domicilio, lugar y fecha de nacimiento, edad, idioma, clave única de registro de población (CURP), género, teléfono particular, teléfono celular, imagen, fotografía, voz y tiempo de residencia. B. Datos afectivos y/o familiares: Parentesco. C. Datos de relaciones familiares: Nombre del padre, madre, tutor, curador o responsable de crianza. D. Datos académicos: Trayectoria educativa, certificados y reconocimientos y/o calificaciones. E. Datos laborales: Ocupación. 2) Los datos recabados de las personas mayores de edad usuarios de los PILARES son: A. Datos identificativos: Nombre, domicilio, lugar y fecha de nacimiento, edad, clave única de registro de población (CURP), género, teléfono particular, teléfono celular, imagen, fotografía, voz y tiempo de residencia. B. Datos afectivos y/o familiares: Parentesco. C. Datos académicos: Trayectoria educativa, certificados y reconocimientos y/o calificaciones. D. Datos laborales: Ocupación. 3) Los datos recabados de personas beneficiarios facilitadores de servicios son: A. Datos identificativos: Nombre, domicilio, lugar y fecha de nacimiento, edad, clave única de registro de población (CURP), género, teléfono particular, imagen, fotografía, voz, teléfono celular, número de licencia de conducir, número de pasaporte, folio nacional (anverso credencial INE) y número identificador (OCR) (reverso de la credencial de elector expedida por el Instituto Nacional Electoral), tiempo de residencia y firma, número de cartilla militar, nombre de los padres. B. Datos electrónicos: Correo electrónico no oficial. C. Datos laborales: Ocupación. D. Datos patrimoniales: Bienes inmuebles y servicios contratados. E. Datos académicos: Trayectoria educativa, certificados y reconocimientos y/o calificaciones. Datos especialmente protegidos (sensibles) de personas menores o en estado de interdicción y mayores de edad usuarios de los PILARES y de las personas beneficiarios facilitadores de servicios son: pertenencia étnica, datos sobre la salud: alergias, discapacidades, uso de aparatos oftalmológicos, ortopédicos, auditivos, diagnóstico psicológico, prótesis, reporte de enfermedades, tratamientos médicos y datos biométricos como lo es la huella digital.

El fundamento para el tratamiento de datos personales es el siguiente: Sección VII.4. del  AVISO MEDIANTE EL CUAL SE DAN A CONOCER LAS REGLAS DE OPERACIÓN DEL PROGRAMA SOCIAL “CIBERESCUELAS EN PILARES, 2019” y AVISO MEDIANTE EL CUAL SE DAN A CONOCER LAS REGLAS DE OPERACIÓN DEL PROGRAMA SOCIAL “EDUCACIÓN PARA LA AUTONOMÍA ECONÓMICA EN PILARES, CIUDAD DE MÉXICO 2019”, publicados en la Gaceta Oficial de la Ciudad de México No. 13, Tomo I, el 18 de enero de 2019.

Para ejercer los derechos de acceso, rectificación, cancelación y oposición, así como la revocación del consentimiento deberá ingresar a la página web http://data.educacion.cdmx/index.php/articulo121/fraccixx para obtener los formatos respectivos o bien acudir a la Unidad de Transparencia ubicada en Av. Chapultepec, número 49, Planta Baja, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06010,  teléfono 51 34 07 70 ext. 1017, al correo electrónico: oip-se@educacion.cdmx.gob.mx.

Las modificaciones al presente aviso estarán disponibles en http://www.educacion.cdmx.gob.mx/transparencia apartado Avisos Integrales de Protección de Datos y en la página https://pilares.cdmx.gob.mx/ 
